/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/footer/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NA: typeof import('naive-ui')['NA']
    'IIon:alertCircleSharp': typeof import('~icons/ion/alert-circle-sharp')['default']
    IIonAlert: typeof import('~icons/ion/alert')['default']
    IIonArrowDownB: typeof import('~icons/ion/arrow-down-b')['default']
    IIonCheckmarkCircle: typeof import('~icons/ion/checkmark-circle')['default']
    'IIonJam:alert': typeof import('~icons/ion/jam-alert')['default']
    IIonPerson: typeof import('~icons/ion/person')['default']
    IIonSearch: typeof import('~icons/ion/search')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    Navbar: typeof import('./src/components/navbar/navbar.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCol: typeof import('naive-ui')['NCol']
    NContainer: typeof import('naive-ui')['NContainer']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NH2: typeof import('naive-ui')['NH2']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NList: typeof import('naive-ui')['NList']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NRow: typeof import('naive-ui')['NRow']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NSpce: typeof import('naive-ui')['NSpce']
    NText: typeof import('naive-ui')['NText']
    NTextOrange500: typeof import('naive-ui')['NTextOrange500']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
