export { default as ProductCard } from './product.vue'
export { default as Question } from './question.vue'
export { default as Detail } from './detail.vue'
export { default as Meet } from './online_meet.vue'
export { default as ActMenu } from './menu_act.vue'
export { default as ActMenu2 } from './menu_act2.vue'